# Generated by Django 2.0 on 2018-08-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='string',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
